# Generated by Django 5.0.1 on 2024-01-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('feat', models.TextField()),
                ('image', models.ImageField(upload_to='song')),
            ],
        ),
    ]
